# Generated by Django 2.0.4 on 2018-07-04 15:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='taller',
            name='estado',
            field=models.PositiveSmallIntegerField(choices=[(1, 'abierto'), (2, 'cerrado')], null=True),
        ),
    ]
