# Generated by Django 2.0.4 on 2018-07-04 15:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0002_taller_estado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='nivel',
            field=models.PositiveSmallIntegerField(choices=[(1, 'ESO'), (2, 'BACHILLER'), (3, 'CFGM'), (4, 'CFGS'), (5, 'PQPI')], null=True),
        ),
    ]
