# Generated by Django 2.0.4 on 2018-07-04 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0003_auto_20180704_1734'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='idTaller',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
    ]
