# Generated by Django 2.0.4 on 2018-07-04 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0004_auto_20180704_1756'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='excede',
            field=models.IntegerField(null=True),
        ),
    ]
