# Generated by Django 2.0.4 on 2018-07-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('talleres', '0005_auto_20180704_1802'),
    ]

    operations = [
        migrations.AlterField(
            model_name='taller',
            name='foto',
            field=models.ImageField(null=True, upload_to=''),
        ),
    ]
