# Generated by Django 2.0.4 on 2018-04-17 18:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alumno',
            fields=[
                ('dni', models.CharField(max_length=8, primary_key=True, serialize=False)),
                ('exp', models.CharField(max_length=10)),
                ('nombre', models.CharField(max_length=50)),
                ('ape1', models.CharField(max_length=50)),
                ('ape2', models.CharField(max_length=50)),
                ('passwd', models.CharField(max_length=10)),
                ('curso', models.IntegerField()),
                ('nivel', models.CharField(max_length=50)),
                ('grupo', models.CharField(max_length=10)),
                ('activo', models.CharField(max_length=1)),
            ],
        ),
        migrations.CreateModel(
            name='AlumnoTaller',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('idAlumno', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Alumno')),
            ],
        ),
        migrations.CreateModel(
            name='Departamento',
            fields=[
                ('idDepart', models.IntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=150)),
            ],
        ),
        migrations.CreateModel(
            name='Taller',
            fields=[
                ('idTaller', models.IntegerField(primary_key=True, serialize=False)),
                ('descrip', models.CharField(max_length=150)),
                ('nivel', models.CharField(max_length=50)),
                ('curso', models.IntegerField()),
                ('maxAlum', models.IntegerField()),
                ('duracion', models.IntegerField()),
                ('jornada', models.IntegerField()),
                ('excede', models.IntegerField()),
                ('idAlumnoTaller', models.ManyToManyField(through='polls.AlumnoTaller', to='polls.Alumno')),
                ('idDepart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Departamento')),
            ],
        ),
        migrations.AddField(
            model_name='alumnotaller',
            name='idTaller',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.Taller'),
        ),
    ]
